Catch exception when mean can't be computed
This is an error, but it should not cause the application to crash.

Traceback (most recent call last):
  File "run.py", line 442, in <module>
    if ntrial > 1: runtrials(ntrial,p['inc_evinput'])
  File "run.py", line 356, in runtrials
    if pcID==0: cattrialoutput() # get/save the averages
  File "run.py", line 338, in cattrialoutput
    ldpl = catdpl()
  File "run.py", line 309, in catdpl
    dpl = np.mean(np.array([np.loadtxt(f) for f in lf]),axis=0)
  File "<__array_function__ internals>", line 6, in mean
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 3257, in mean
    out=out, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/_methods.py", line 151, in _mean
    ret = umr_sum(arr, axis, dtype, out, keepdims)
ValueError: operands could not be broadcast together with shapes (5268,4) (5252,4)